services:
  nginx-gateway:
    image: "$DOCKER_USERNAME/nginx:$TAG"
    container_name: nginx-gateway
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /home/ubuntu/website/logs:/var/log/nginx
      - /home/ubuntu/website/nginx/certificates:/etc/letsencrypt
      - /home/ubuntu/website/nginx/certificates-data:/data/certbot
      - /home/ubuntu/website/nginx/.htpasswd:/etc/nginx/.htpasswd
    networks:
      - webnet
    restart: always

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - /home/ubuntu/website/nginx/certificates:/etc/letsencrypt
      - /home/ubuntu/website/nginx/certificates-data:/data/certbot
    entrypoint: >
      sh -c "
        while :; do
          certbot renew;
          sleep 12h & wait $${!};
        done"
    networks:
      - webnet
    restart: on-failure

  minio:
    image: minio/minio
    container_name: minio
    expose:
      - "9000"   # S3 API
      - "9001"   # MinIO Console
    environment:
      MINIO_ROOT_USER: $MINIO_ROOT_USER
      MINIO_ROOT_PASSWORD: $MINIO_ROOT_PASSWORD
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    networks:
      webnet:
      vpn_custom_network:
        ipv4_address: 10.13.14.3
    restart: always

  mongodb:
    image: mongo:6
    container_name: mongo
    expose:
      - 27017
    environment:
      MONGO_INITDB_DATABASE: images
      MONGO_INITDB_ROOT_USERNAME: $MONGO_INITDB_ROOT_USERNAME
      MONGO_INITDB_ROOT_PASSWORD: $MONGO_INITDB_ROOT_PASSWORD
    volumes:
      - mongo_data:/data/db
    networks:
      - webnet
    restart: always

networks:
  webnet:
  vpn_custom_network:
    external: true

volumes:
  minio_data:
  mongo_data:
